version: "3.8"

services:
  item-app:
    image: hanifrosidi/item-app:1
    container_name: item-app
    ports:
      - "80:8080"
    depends_on:
      - item-db

  item-db:
    image: mongo:3
    container_name: item-db
    volumes:
      - app-db:/data/db

volumes:
  app-db:
