# Versi API Kubernetes yang digunakan
apiVersion: v1

# Jenis resource kubernetes
kind: Secret

# Metadata resource
metadata:
  # Nama secret
  name: mongodb-secret

# Tipe Secret
# Opaque digunakan untuk menyimpan data key-value umum
type: Opaque

# Data rahasia yang disimpan
data:
  # Username root MongoDB dalam format Base64
  MONGO_ROOT_USERNAME: YWRtaW4=
  # Password root MongoDB dalam format Base64
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==
